<?php
require('Admin/connection.inc.php');
require('Admin/functions.inc.php');
unset($_SESSION['USER_LOGIN']);
unset($_SESSION['USER_ID']);
unset($_SESSION['USER_NAME']);
header('location:index-0.php');
die();
?>